name: SRComp Validate Action
description: A GitHub Action to validate a compstate.
runs:
  using: composite
  steps:
  

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: ${{ github.action_path }}/requirements.txt

    - name: Install Dependencies
      shell: bash
      run: pip install requirements.txt

    - name: Run Compstate Validation
      shell: bash
      run: ${{ github.action_path }}/validate.py .
